version: '3'

services:
  redis-server:
    image: 'redis'
  node-app:
    build:
      context: './'
      dockerfile: 'nodejs-dockerfile.debug'
    ports:
      - '5000:8080'
    volumes: 
      - .:/usr/app/shared-volume
  